# Generated by Django 5.2.2 on 2025-06-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='Забанен'),
        ),
        migrations.AddField(
            model_name='client',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Юзернейм'),
        ),
    ]
