# Generated by Django 5.2.2 on 2025-06-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_client_is_banned_client_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='next_ability',
            field=models.DateTimeField(blank=True, help_text='Если null\xa0— ограничение ещё не применялось', null=True, verbose_name='Когда можно будет снова публиковать'),
        ),
    ]
