# Generated by Django 5.2.2 on 2025-06-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_category_alter_shop_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='next_ability_automoto',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда можно будет снова публиковать AUTO/MOTO'),
        ),
        migrations.AddField(
            model_name='client',
            name='next_ability_housing',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда можно будет снова публиковать HOUSING'),
        ),
        migrations.AddField(
            model_name='client',
            name='next_ability_techno',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда можно будет снова публиковать TECHNO'),
        ),
    ]
