# Generated by Django 5.2.2 on 2025-06-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_client_next_ability_automoto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='next_ability_job',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда можно будет снова публиковать JOB'),
        ),
    ]
