# Generated by Django 5.2.2 on 2025-07-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_pricingrule_timesurcharge_courierorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierorder',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('assigned', 'Назначен'), ('to_a', 'В пути до точки А'), ('to_b', 'В пути до точки Б'), ('arrived', 'Приехал'), ('completed', 'Завершён')], default='new', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
