# Generated by Django 5.2.2 on 2025-08-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_courierorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='point_a_lat',
            field=models.FloatField(default=1, verbose_name='Широта точки А'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='point_a_lng',
            field=models.FloatField(default=1, verbose_name='Долгота точки А'),
            preserve_default=False,
        ),
    ]
